Repository nuxeo/nuxeo-elements, pull requests merged in 2025-01, with the labels that each got.

#1021 ELEMENTS-1776: fix column sort arrow and sequence number overlap
  ui/nuxeo-data-table/data-table-cell.js
  ui/nuxeo-data-table/data-table-column-sort.js
  ui/nuxeo-data-table/data-table-column.js
Labels: 3.1.x

#1022 ELEMENTS-1776: BACKWARD PORT: fix column sort arrow and sequence number overlap
  ui/nuxeo-data-table/data-table-cell.js
  ui/nuxeo-data-table/data-table-column-sort.js
  ui/nuxeo-data-table/data-table-column.js
Labels: 3.0.x

#1030 ELEMENTS-1781: Fix alignment & style defects in nuxeo-video-conversions lts 2023
  ui/nuxeo-video/nuxeo-video-conversions.js
Labels: 3.1.x

#1029 ELEMENTS-1781: Fix alignment & style defects in nuxeo-video-conversions lts 2021
  ui/nuxeo-video/nuxeo-video-conversions.js
Labels: 3.0.x

#1024 WEBUI-1616: rtl support
  ui/nuxeo-document-comments/nuxeo-document-comment.js
  ui/nuxeo-document-permissions/nuxeo-document-acl-table.js
  ui/nuxeo-document-permissions/nuxeo-document-permissions.js
  ui/nuxeo-document-thumbnail/nuxeo-document-thumbnail.js
  ui/nuxeo-path-suggestion/nuxeo-path-suggestion.js
  ui/nuxeo-tree/nuxeo-tree-node.js
  ui/nuxeo-user-group-management.js
  ui/nuxeo-video/nuxeo-video-conversions.js
  ui/widgets/nuxeo-card.js
  ui/widgets/nuxeo-directory-suggestion.js
  ui/widgets/nuxeo-html-editor.js
  ui/widgets/nuxeo-selectivity.js
  ui/widgets/nuxeo-user-tag.js
  ui/widgets/quill/quill-snow.js
Labels: i18
